create table users (
    id            bigint generated by default as identity,
    type          varchar(15)  not null,
    name          varchar(120) not null,
    email         varchar(150) not null,
    password_hash varchar(44)  not null,
    salt          varchar(24)  not null,
    active        boolean      not null default true,
    created_at    timestamp(6) not null,
    constraint pk_users primary key (id),
    constraint uk_users_email unique (email),
    constraint ck_users_type check (type in ('CUSTOMER', 'EMPLOYEE'))
);

create table customers (
    user_id bigint      not null,
    cpf     varchar(11) not null,
    phone   varchar(11) not null,
    constraint pk_customers primary key (user_id),
    constraint fk_customers_user foreign key (user_id) references users (id),
    constraint uk_customers_cpf unique (cpf)
);

create table employees (
    user_id    bigint not null,
    birth_date date   not null,
    constraint pk_employees primary key (user_id),
    constraint fk_employees_user foreign key (user_id) references users (id)
);

create table addresses (
    id          bigint generated by default as identity,
    customer_id bigint       not null,
    zip_code    varchar(8)   not null,
    street      varchar(150) not null,
    number      varchar(10)  not null,
    complement  varchar(60),
    district    varchar(80)  not null,
    city        varchar(80)  not null,
    state       varchar(2)   not null,
    constraint pk_addresses primary key (id),
    constraint fk_addresses_customer foreign key (customer_id) references customers (user_id),
    constraint uk_addresses_customer unique (customer_id)
);
