create table maintenance_request (
    id                      bigint       generated by default as identity,
    customer_id             bigint       not null,
    category_id             bigint       not null,
    current_employee_id     bigint,                -- quem faz o orcamento
    status                  varchar(20)  not null,
    equipment_description   varchar(200) not null,
    defect_description      text         not null,
    opening_date_time       timestamp(6) not null,
    quote_value             numeric(10,2),
    rejection_reason        text,
    maintenance_description text,
    customer_instructions   text,
    payment_date_time       timestamp(6),
    constraint pk_maintenance_request primary key (id),
    constraint fk_maintenance_request_customer foreign key (customer_id)         references customers (user_id),
    constraint fk_maintenance_request_category foreign key (category_id)         references category (id),
    constraint fk_maintenance_request_employee foreign key (current_employee_id) references employees (user_id),
    -- estado corrente. Virou check em vez da tabela ESTADO_SOLICITACAO do
    constraint ck_maintenance_request_status check (status in (
        'ABERTA', 'ORCADA', 'REJEITADA', 'APROVADA', 'REDIRECIONADA', 'ARRUMADA', 'PAGA', 'FINALIZADA'
    )),
    -- pago <-> tem data de pagamento, nos dois sentidos. Sem isso uma linha PAGA
    -- com data nula sumiria do group by do RF019 sem erro nenhum, so com o total
    -- errado.
    constraint ck_maintenance_request_payment check (
        (status in ('PAGA', 'FINALIZADA') and payment_date_time is not null) or
        (status not in ('PAGA', 'FINALIZADA') and payment_date_time is null)
    )
);
