create table request_history (
    id                      bigint       generated by default as identity,
    request_id              bigint       not null,
    previous_status         varchar(20),
    new_status              varchar(20)  not null,
    author_id               bigint,
    destination_employee_id bigint,
    date_time               timestamp(6) not null,
    notes                   text,

    constraint pk_request_history primary key (id),
    constraint fk_request_history_request foreign key (request_id) references maintenance_request (id),
    constraint fk_request_history_author foreign key (author_id) references users (id),
    constraint fk_request_history_dest_emp foreign key (destination_employee_id) references employees (user_id),

    constraint ck_req_hist_prev_status check (previous_status in (
        'ABERTA', 'ORCADA', 'REJEITADA', 'APROVADA', 'REDIRECIONADA', 'ARRUMADA', 'PAGA', 'FINALIZADA'
    )),
    constraint ck_req_hist_new_status check (new_status in (
        'ABERTA', 'ORCADA', 'REJEITADA', 'APROVADA', 'REDIRECIONADA', 'ARRUMADA', 'PAGA', 'FINALIZADA'
    ))
);
